battery_wheels/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = patterns('',

    url(r'^$', 'price.views.home', name='home'),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^price/', include('price.urls')),
    url(r'^contact/', include('contact.urls')),
)
urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

contact/urls.py
from django.conf.urls import url
from contact.views import ContactView

urlpatterns = [
    url(r'^send/$', ContactView.as_view(), name='contact'),
]

price/urls.py
from django.conf.urls import url

from price.views import BatterysView, WheelsView, TyresView, goods_filter, info

urlpatterns = [
    url(r'^batterys/icons/$', BatterysView.as_view(template_name='batteries_as_icons.html'), name='battery_icons'),
    url(r'^batterys/table/$', BatterysView.as_view(template_name= 'batteries_as_table.html'), name='battery_table'),
    url(r'^wheels/icons/$', WheelsView.as_view(template_name='wheels_as_icons.html'), name='wheels_icons'),
    url(r'^wheels/table/$', WheelsView.as_view(template_name='wheels_as_table.html'), name='wheels_table'),
    url(r'^tyres/icons/$', TyresView.as_view(template_name='tyres_as_icons.html'), name='tyres_icons'),
    url(r'^tyres/table/$', TyresView.as_view(template_name='tyres_as_table.html'), name='tyres_table'),
    url(r'^filter/', goods_filter, name='goods_filter'),
    url(r'^info/', info, name='info'),
]

contact/models.py
from django.db import models


class Contact(models.Model):
    person_name = models.CharField(verbose_name='Имя', max_length=100)
    person_last_name = models.CharField(verbose_name='Фамилия', max_length=100)
    person_phone = models.CharField(verbose_name='Телефон', max_length=20)
    person_mail = models.EmailField(verbose_name='E-mail', max_length=40)

    def __str__(self):
        return self.person_name + " " + self.person_last_name

    class Meta:
        verbose_name = "Контакт"
        verbose_name_plural = 'Контакты'

contact/forms.py
from django import forms
import re
from django.core.mail import send_mail
from battery_wheels.settings import FEEDBACK_RECIPIENTS


class ContactForm(forms.Form):
    subject = forms.CharField(max_length=100, widget=forms.TextInput(attrs={'class': 'form-control'}))
    message = forms.CharField(widget=forms.Textarea(attrs={'class': 'form-control'}))
    sender = forms.EmailField(widget=forms.TextInput(attrs={'class': 'form-control'}))

    def send_mail(self):
        send_mail(
            self.cleaned_data['subject'],
            self.cleaned_data['sender'] + ' прислал вам сообщение на чистик-спб: ' + self.cleaned_data['message'],
            self.cleaned_data['sender'],
            FEEDBACK_RECIPIENTS
        )

contact/views.py
from django.http import JsonResponse
from django.views.generic import FormView

from contact.models import Contact
from slider.models import Slider
from .forms import ContactForm


class ContactView(FormView):
    template_name = 'contact.html'
    form_class = ContactForm
    success_url = '#'

    def form_valid(self, form):
        form.send_mail()
        return JsonResponse({'status': 'Ok',})

    def form_invalid(self, form):
        return JsonResponse({'status': 'error', 'errors': form.errors})

    def get_context_data(self, **kwargs):
        context = super(ContactView, self).get_context_data(**kwargs)
        context['slider'] = Slider.objects.all()
        context['contacts'] = Contact.objects.all()
        return context

contact/templates/contact.html
{% extends 'base.html' %}


{% block title %} Чистик-спб - Контакты {% endblock %}

{% block content %}

    <div class="container content" xmlns="http://www.w3.org/1999/html">
        <div class="row margin-bottom-30">
            <div class="col-md-9 mb-margin-bottom-30">
                <div class="headline"><h2>Свяжитесь с нами!</h2></div>
                <p>Вы можете оставить свой отзыв или предложение здесь:</p><br>
                <table>
                    <form class="sky-form contact-style" method="post" action="">
                        {% csrf_token %}
                        {{ form.non_field_errors }}

                        <div class="fieldWrapper row sky-space-20">
                            <div class="col-md-7 col-md-offset-0">
                                <label for="id_subject">Ваше имя: </label>
                                {% if form.subject.errors %}
                                    <div class="has-error fieldWrapper">
                                        {{ form.subject }}
                                        <span class="help-inline">{{ form.subject.errors }}</span>
                                    </div>
                                {% else %}
                                    <div class="has-success fieldWrapper">
                                        {{ form.subject }}
                                    </div>
                                {% endif %}
                            </div>
                        </div>

                        <div class="fieldWrapper row sky-space-20">
                            <div class="col-md-7 col-md-offset-0">
                                <label for="id_sender">Ваш e-mail:</label>
                                {% if form.sender.errors %}
                                    <div class="has-error fieldWrapper">
                                        {{ form.sender }}
                                        <span class="help-inline">{{ form.sender.errors }}</span>
                                    </div>
                                {% else %}
                                    <div class="has-success fieldWrapper">
                                        {{ form.sender }}
                                    </div>
                                {% endif %}
                            </div>
                        </div>

                        <div class="fieldWrapper row sky-space-20">
                            <div class="col-md-11 col-md-offset-0">
                                <label for="id_message">Ваше сообщение: </label>
                                {% if form.message.errors %}
                                    <div class="has-error fieldWrapper">
                                        {{ form.message }}
                                        <span class="help-inline">{{ form.message.errors }}</span>
                                    </div>
                                {% else %}
                                    <div class="has-success fieldWrapper">
                                        {{ form.message }}
                                    </div>
                                {% endif %}
                            </div>
                        </div>
                        <br/>

                        <button class="btn btn-success contact_btn" type="submit">Отправить сообщение</button>
                    </form>
                </table>
            </div><!--/col-md-9-->

            <div class="col-md-3">
                <!-- Contacts -->
                <div class="headline"><h2>Наши контакты</h2></div>
                {% if contacts %}
                    {% for contact in contacts %}
                        <ul class="list-unstyled who margin-bottom-30">
                            <li><i class="fa fa-user"></i> {{ contact.person_name }}</li>
                            <li><i class="fa fa-phone"></i> {{ contact.person_phone }}</li>
                            <li><i class="fa fa-envelope"></i> {{ contact.person_mail }}</li>
                            <li><i class="fa fa-globe"></i> www.mirsim.ru</li>
                        </ul>
                    {% endfor %}
                {% else %}
                    <p>Извините, в данный момент контакты недоступны.</p>
                    <p>Воспользуйтесь формой обратной связи</p>
                {% endif %}

                <!-- Время работы -->
                {#                <div class="headline"><h2>Время работы</h2></div>#}
                {#                <ul class="list-unstyled margin-bottom-30">#}
                {#                	<li><strong>Понедельник-Пятница:</strong> 10:00 - 20:00</li>#}
                {#                	<li><strong>Суббота:</strong> 10:00 - 18:00</li>#}
                {#                	<li><strong>Воскресенье:</strong>11:00 - 17:00</li>#}
                {#                </ul>#}

            </div><!--/col-md-3-->
        </div><!--/row-->
    </div>

{% endblock %}

contact/templates/feedback.html
<div class="global-container-feedback hidden-sm" xmlns="http://www.w3.org/1999/html">
    <div class="container-feedback">
        {% if contacts %}
            {% for contact in contacts %}
                <table>
                    <tr>
                        <td>
                            <i class="fa fa-user"></i> {{ contact.person_name }}
                        </td>
                        <td>
                            <i class="fa fa-phone"></i> {{ contact.person_phone }}
                        </td>
                    </tr>
                    <tr>
                        <td colspan="2">
                            <i class="fa fa-envelope "></i> {{ contact.person_mail }}
                        </td>
                    </tr>
                </table>
                <br>
            {% endfor %}
        {% else %}
            <p>Извините, в данный момент контакты недоступны.</p>
            <p>Воспользуйтесь формой обратной связи</p>
        {% endif %}
        <p class="feedback-text">
            <b>Время работы:</b>
        </p>
        <p class="feedback-text">
            Ежедневно 8:00 - 20:00
        </p>
        <div class="feedback-form">
            <form class="sky-form contact-style add-order-form" id="add-order-form" method="post"
                  action="{% url 'contact' %}">
                {% csrf_token %}
                <div class="fieldWrapper row sky-space-20">
                    <div class="col-md-11 col-md-offset-0">
                        <div id="div_id_subject" class="form-group">
                            <label for="id_subject" class="control-label">
                                Ваше имя<span> *</span>
                            </label>
                            <div class="controls">
                                <input class="form-control" id="id_subject" maxlength="100" name="subject" type="text">
                            </div>
                        </div>
                        <div id="div_id_message" class="form-group">
                            <label for="id_message" class="control-label">
                                Сообщение<span>*</span>
                            </label>
                            <div class="controls">
                                <textarea class="form-control textarea" cols="30" id="id_message" name="message"
                                          rows="6">
                                </textarea>
                            </div>
                        </div>
                        <div id="div_id_sender" class="form-group">
                            <label for="id_sender" class="control-label">
                                E-mail<span>*</span> </label>
                            <div class="controls">
                                <input class="form-control" id="id_sender" name="sender" type="text">
                            </div>
                        </div>
                        <button class="btn btn-success contact_btn" type="submit">
                            Отправить сообщение
                        </button>
                    </div>
                </div>
            </form>
        </div>
        <p class="feedback-text">
            * - Поля обязательные для заполнения
        </p>
    </div>
    <div class="fb-feedback"><span class="feedback">Контакты</span></div>
</div>